exec:
  min_output_tasks: 1
in:
  type: mysql
  host: mysql
  user: root
  password: root
  database: app
  query: |
    SELECT
      id,
      account,
      time,
      purchase,
      comment
    FROM samples
out:
  type: postgresql
  host: postgres
  user: postgres
  password: postgres
  database: postgres
  table: samples
  mode: insert
